/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "importgl.h"
/* Header for class my_exercise_opengl_JniWrapper */

#ifndef _Included_my_exercise_opengl_JniWrapper
#define _Included_my_exercise_opengl_JniWrapper


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_exercise_opengl_JniWrapper
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_my_exercise_opengl_JniWrapper_nativeInit
(JNIEnv *, jclass);

/*
 * Class:     my_exercise_opengl_JniWrapper
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_exercise_opengl_JniWrapper_nativeRender
(JNIEnv *, jclass, jint);

/*
 * Class:     my_exercise_opengl_JniWrapper
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_my_exercise_opengl_JniWrapper_nativeResize
(JNIEnv *, jclass, jint, jint);

/*
 * Class:     my_exercise_opengl_JniWrapper
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_exercise_opengl_JniWrapper_nativeDone
(JNIEnv *, jclass);


/*
 * Class:     my_exercise_opengl_JniWrapper
 * Method:    feedTexture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_exercise_opengl_JniWrapper_feedPosition
(JNIEnv *, jclass, jintArray);



#ifdef __cplusplus
}
#endif
#endif
