/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_exercise_videoprocess_VideoFrameUnit */

#ifndef _Included_my_exercise_videoprocess_VideoFrameUnit
#define _Included_my_exercise_videoprocess_VideoFrameUnit
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_my_exercise_videoprocess_VideoFrameUnit_initVideoCtx(JNIEnv *, jobject );


JNIEXPORT void JNICALL Java_my_exercise_videoprocess_VideoFrameUnit_freeVideoCtx(JNIEnv * , jobject );

  JNIEXPORT jintArray JNICALL Java_my_exercise_videoprocess_VideoFrameUnit_getVideoFrame(JNIEnv * , jobject ); 


  JNIEXPORT jint JNICALL Java_my_exercise_videoprocess_VideoFrameUnit_logFileInfo(JNIEnv * , jobject , jstring, jint, jint );

/*
 * Class:     my_exercise_videoprocess_VideoFrameUnit
 * Method:    rgb565ToRgba
 * Signature: ([I[II)V
 */
JNIEXPORT void JNICALL Java_my_exercise_videoprocess_VideoFrameUnit_rgb565ToRgba
  (JNIEnv *, jclass, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
